package com.buwang.app.core.export

import com.buwang.app.core.crypto.CryptoManager
import com.buwang.app.data.local.dao.ConversationDao
import com.buwang.app.data.local.dao.MessageDao
import com.buwang.app.data.local.dao.PersonaDao
import com.buwang.app.data.local.entity.ConversationEntity
import com.buwang.app.data.local.entity.MessageEntity
import com.buwang.app.data.local.entity.PersonaEntity
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import kotlinx.coroutines.flow.first
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.io.FileOutputStream
import java.util.UUID
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream
import javax.inject.Inject
import javax.inject.Singleton

/**
 * 数据导入导出引擎
 *
 * 导出格式：.bwbackup（ZIP + AES-256 加密）
 * 导出内容：所有角色、会话、消息的完整 JSON
 *
 * 文件结构：
 * ```
 * buwang_backup.json  ← 明文数据（ZIP内）
 * ```
 *
 * 流程：
 * 导出：数据 → JSON → ZIP → AES加密 → .bwbackup
 * 导入：.bwbackup → AES解密 → ZIP解压 → JSON → 数据库
 */
@Singleton
class ExportEngine @Inject constructor(
    private val personaDao: PersonaDao,
    private val conversationDao: ConversationDao,
    private val messageDao: MessageDao,
    private val cryptoManager: CryptoManager
) {

    private val moshi = Moshi.Builder()
        .addLast(KotlinJsonAdapterFactory())
        .build()

    /**
     * 导出所有数据到加密文件
     *
     * @param outputFile 输出文件路径
     * @param password 用户设置的加密密码
     * @return 导出的数据统计信息
     */
    suspend fun exportAll(outputFile: File, password: String): ExportResult {
        // 1. 收集所有数据
        val personas = personaDao.getAllPersonas().first()
        val conversations = conversationDao.getAllConversations().first()

        val messagesByConv = mutableMapOf<String, List<MessageEntity>>()
        for (conv in conversations) {
            messagesByConv[conv.id] = messageDao.getLatestMessages(conv.id, Int.MAX_VALUE)
        }

        // 2. 构建 JSON
        val json = buildExportJson(personas, conversations, messagesByConv)

        // 3. JSON → ZIP
        val zipBytes = createZip(json)

        // 4. ZIP → AES 加密 → 写入文件
        val encrypted = cryptoManager.encryptWithPassword(password, zipBytes)
        outputFile.writeBytes(encrypted)

        return ExportResult(
            personaCount = personas.size,
            conversationCount = conversations.size,
            messageCount = messagesByConv.values.sumOf { it.size },
            fileSizeBytes = encrypted.size
        )
    }

    /**
     * 从加密文件导入数据
     *
     * @param inputFile .bwbackup 文件
     * @param password 解密密码
     * @param conflictStrategy 冲突处理策略
     * @return 导入结果
     */
    suspend fun importAll(
        inputFile: File,
        password: String,
        conflictStrategy: ConflictStrategy = ConflictStrategy.KEEP_BOTH
    ): ImportResult {
        // 1. 读取加密文件
        val encrypted = inputFile.readBytes()

        // 2. AES 解密
        val zipBytes = cryptoManager.decryptWithPassword(password, encrypted)

        // 3. ZIP 解压
        val json = extractZip(zipBytes)

        // 4. JSON → 数据库
        return parseAndImport(json, conflictStrategy)
    }

    /**
     * 导出单个角色为 SillyTavern 兼容格式
     */
    suspend fun exportSingleAsST(personaId: String, outputFile: File): Boolean {
        val persona = personaDao.getPersonaByIdOnce(personaId) ?: return false

        // 构建 ST V2 格式 JSON
        val stJson = JSONObject().apply {
            put("spec", "chara_card_v2")
            put("spec_version", "2.0")
            put("data", JSONObject().apply {
                put("name", persona.name)
                put("description", persona.description)
                put("personality", extractPersonalitySummary(persona.personalityParams))
                put("first_mes", generateFirstMessage(persona))
                put("mes_example", "")
                put("creator_notes", "Generated by 不忘 App")
                put("system_prompt", persona.systemPromptTemplate)
                put("post_history_instructions", "")
                put("alternate_greetings", JSONArray())
                put("tags", JSONArray())
                put("creator", "不忘 App")
                put("character_version", "1.0")
            })
        }

        outputFile.writeText(stJson.toString(2))
        return true
    }

    // ===== 私有方法 =====

    private fun buildExportJson(
        personas: List<PersonaEntity>,
        conversations: List<ConversationEntity>,
        messagesByConv: Map<String, List<MessageEntity>>
    ): String {
        val root = JSONObject().apply {
            put("version", "1.0")
            put("exported_at", System.currentTimeMillis())
            put("app", "不忘App")

            put("personas", JSONArray().apply {
                personas.forEach { persona ->
                    put(JSONObject().apply {
                        put("id", persona.id)
                        put("name", persona.name)
                        put("avatar_path", persona.avatarPath ?: "")
                        put("description", persona.description)
                        put("source_type", persona.sourceType)
                        put("source_mbti_type", persona.sourceMbtiType ?: "")
                        put("personality_params", persona.personalityParams)
                        put("system_prompt_template", persona.systemPromptTemplate)
                        put("created_at", persona.createdAt)
                        put("updated_at", persona.updatedAt)
                    })
                }
            })

            put("conversations", JSONArray().apply {
                conversations.forEach { conv ->
                    put(JSONObject().apply {
                        put("id", conv.id)
                        put("persona_id", conv.personaId)
                        put("title", conv.title)
                        put("created_at", conv.createdAt)
                        put("updated_at", conv.updatedAt)

                        put("messages", JSONArray().apply {
                            messagesByConv[conv.id]?.forEach { msg ->
                                put(JSONObject().apply {
                                    put("id", msg.id)
                                    put("conversation_id", msg.conversationId)
                                    put("role", msg.role)
                                    put("content", msg.content)
                                    put("timestamp", msg.timestamp)
                                    put("metadata", msg.metadata ?: "")
                                })
                            }
                        })
                    })
                }
            })
        }

        return root.toString(2)
    }

    private fun createZip(content: String): ByteArray {
        val baos = java.io.ByteArrayOutputStream()
        ZipOutputStream(baos).use { zos ->
            zos.putNextEntry(ZipEntry("buwang_backup.json"))
            zos.write(content.toByteArray(Charsets.UTF_8))
            zos.closeEntry()
        }
        return baos.toByteArray()
    }

    private fun extractZip(zipBytes: ByteArray): String {
        val bais = java.io.ByteArrayInputStream(zipBytes)
        ZipInputStream(bais).use { zis ->
            val entry = zis.nextEntry ?: throw ExportException("备份文件格式错误：未找到数据")
            if (entry.name != "buwang_backup.json") {
                throw ExportException("备份文件格式错误：文件不匹配")
            }
            return zis.readBytes().toString(Charsets.UTF_8)
        }
    }

    private suspend fun parseAndImport(json: String, conflictStrategy: ConflictStrategy): ImportResult {
        val root = JSONObject(json)
        var personaCount = 0
        var conversationCount = 0
        var messageCount = 0
        var skippedPersonas = 0
        var skippedConversations = 0
        val conflicts = mutableListOf<String>()

        // 导入角色
        val personasArray = root.getJSONArray("personas")
        for (i in 0 until personasArray.length()) {
            val p = personasArray.getJSONObject(i)
            val personaId = p.getString("id")

            val existing = personaDao.getPersonaByIdOnce(personaId)
            if (existing != null) {
                when (conflictStrategy) {
                    ConflictStrategy.OVERWRITE -> {
                        personaDao.insert(buildPersonaEntity(p, personaId))
                        personaCount++
                        conflicts.add("角色「${p.getString("name")}」已覆盖")
                    }
                    ConflictStrategy.KEEP_BOTH -> {
                        val newId = UUID.randomUUID().toString()
                        personaDao.insert(buildPersonaEntity(p, newId))
                        personaCount++
                        conflicts.add("角色「${p.getString("name")}」已保留为新副本")
                    }
                    ConflictStrategy.SKIP -> {
                        skippedPersonas++
                    }
                }
            } else {
                personaDao.insert(buildPersonaEntity(p, personaId))
                personaCount++
            }
        }

        // 导入会话和消息
        val conversationsArray = root.getJSONArray("conversations")
        for (i in 0 until conversationsArray.length()) {
            val c = conversationsArray.getJSONObject(i)
            val convId = c.getString("id")
            val personaId = c.getString("persona_id")

            // 检查关联角色是否存在
            val personaExists = personaDao.getPersonaByIdOnce(personaId) != null
            if (!personaExists) {
                skippedConversations++
                continue
            }

            val existingConv = conversationDao.getConversationById(convId)
            val finalConvId = if (existingConv != null) {
                when (conflictStrategy) {
                    ConflictStrategy.OVERWRITE -> convId
                    ConflictStrategy.KEEP_BOTH -> UUID.randomUUID().toString()
                    ConflictStrategy.SKIP -> {
                        skippedConversations++
                        continue
                    }
                }
            } else {
                convId
            }

            // 插入会话
            conversationDao.insert(
                ConversationEntity(
                    id = finalConvId,
                    personaId = personaId,
                    title = c.getString("title"),
                    createdAt = c.getLong("created_at"),
                    updatedAt = c.getLong("updated_at")
                )
            )
            conversationCount++

            // 插入消息
            val messagesArray = c.getJSONArray("messages")
            val messages = mutableListOf<MessageEntity>()
            for (j in 0 until messagesArray.length()) {
                val m = messagesArray.getJSONObject(j)
                messages.add(
                    MessageEntity(
                        id = if (conflictStrategy == ConflictStrategy.KEEP_BOTH)
                            UUID.randomUUID().toString()
                        else
                            m.getString("id"),
                        conversationId = finalConvId,
                        role = m.getString("role"),
                        content = m.getString("content"),
                        timestamp = m.getLong("timestamp"),
                        metadata = m.optString("metadata", null)
                    )
                )
            }
            if (messages.isNotEmpty()) {
                messageDao.insertAll(messages)
                messageCount += messages.size
            }
        }

        return ImportResult(
            personaCount = personaCount,
            conversationCount = conversationCount,
            messageCount = messageCount,
            skippedPersonas = skippedPersonas,
            skippedConversations = skippedConversations,
            conflicts = conflicts
        )
    }

    private fun buildPersonaEntity(json: JSONObject, id: String): PersonaEntity {
        return PersonaEntity(
            id = id,
            name = json.getString("name"),
            avatarPath = json.optString("avatar_path", null)?.ifEmpty { null },
            description = json.getString("description"),
            sourceType = json.getString("source_type"),
            sourceMbtiType = json.optString("source_mbti_type", null)?.ifEmpty { null },
            personalityParams = json.getString("personality_params"),
            systemPromptTemplate = json.getString("system_prompt_template"),
            createdAt = json.getLong("created_at"),
            updatedAt = json.getLong("updated_at")
        )
    }

    private fun extractPersonalitySummary(personalityParamsJson: String): String {
        return try {
            val params = JSONObject(personalityParamsJson)
            buildString {
                append("开放性: ${params.optInt("openness", 50)}%")
                append(", 尽责性: ${params.optInt("conscientiousness", 50)}%")
                append(", 外向性: ${params.optInt("extraversion", 50)}%")
                append(", 宜人性: ${params.optInt("agreeableness", 50)}%")
                append(", 神经质: ${params.optInt("neuroticism", 50)}%")
            }
        } catch (e: Exception) {
            "人格参数"
        }
    }

    private fun generateFirstMessage(persona: PersonaEntity): String {
        return "你好！我是${persona.name}，很高兴认识你。${persona.description}"
    }
}

/**
 * 导出结果
 */
data class ExportResult(
    val personaCount: Int,
    val conversationCount: Int,
    val messageCount: Int,
    val fileSizeBytes: Int
)

/**
 * 导入结果
 */
data class ImportResult(
    val personaCount: Int,
    val conversationCount: Int,
    val messageCount: Int,
    val skippedPersonas: Int = 0,
    val skippedConversations: Int = 0,
    val conflicts: List<String> = emptyList()
)

/**
 * 冲突处理策略
 */
enum class ConflictStrategy {
    /** 覆盖已有数据 */
    OVERWRITE,
    /** 保留两者（生成新ID） */
    KEEP_BOTH,
    /** 跳过冲突项 */
    SKIP
}

// ExportException 定义在 com.buwang.app.core.crypto 包中
